USE testdb3;

SHOW TABLES;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS users_wallet;

SELECT * FROM users_wallet;

CREATE TABLE users1
(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

ALTER TABLE users1 ADD COLUMN email VARCHAR(255) NOT NULL UNIQUE;
ALTER TABLE users1 ADD COLUMN isActive BOOLEAN DEFAULT TRUE;

SELECT * FROM users1;